### PR TITLE
Fix correctness test

### LINKED ISSUE #27: Correctness test is broken
It fails after #26 since we have an extra frame (`glue::registers`). Fixing that is trivial (ee6030a). But before #26 it wasn't testing much anyway because the `backtrace` crate uses our `_Unwind_Backtrace`.

### PR DESCRIPTION
**Pull request by philipc**
It is using the system unwinder for the reference now that libunwind_shim is disabled by #35.

Also move the assert out of the callback, because unwinding in the callback doesn't work.

Fixes #27

### CODE REVIEW

File: unwind/tests/correctness.rs [hunk 1]
```diff
@@ -25,24 +25,32 @@ fn test_frame_3() {
         println!("{:08x}", i);
     }
     println!();
-        
-    DwarfUnwinder::default().trace(move |frames| {
+
+    let mut ref_trace_len = ref_trace.len();
+    // Haven't investigated why this has a trailing zero.
```
Comment (bjorn3) [inline unwind/tests/correctness.rs]: I have this too in https://github.com/bjorn3/pretty_backtrace/, it seems a property of `libbacktrace`.
